fix: 修改下载源

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   build-and-deploy:
-    runs-on: self-hosted
+    runs-on: self-hosted # 使用自托管的 Runner
 
     steps:
       - name: Checkout code
@@ -19,15 +19,27 @@ jobs:
           node-version: 20
           cache: "npm"
 
+      - name: Set npm registry
+        run: npm config set registry https://registry.npmmirror.com
+
       - name: Install dependencies
-        run: npm ci
+        run: npm ci --verbose
 
       - name: Build project
         run: npm run build
 
       - name: Update site directory
         run: |
+          # 使用 GitHub Variables 中定义的路径
           SITE_PATH="${{ vars.SITE_ROOT }}"
+          
+          # 检查路径是否为空，防止误删根目录
+          if [ -z "$SITE_PATH" ]; then
+            echo "Error: SITE_ROOT variable is not set."
+            exit 1
+          fi
+
+          echo "Deploying to $SITE_PATH"
           sudo rm -rf $SITE_PATH/*
           sudo cp -r dist/* $SITE_PATH/
           sudo chown -R www:www $SITE_PATH/
